config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :jobs
  root 'jobs#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :jobs
end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
    before_action :find_job, only: [:show, :edit, :update, :destroy]
    def index
        if params[:category].blank?
            @jobs = Job.all.order("created_at DESC")
        else
            @category_id = Category.find_by(name: params[:category]).id
            @jobs = Job.where(category_id: @category_id).order("created_at DESC")
        end
    end

    def show
    end

    def new
        @job = Job.new
    end

    def create
        @job = Job.new(jobs_params)

        if @job.save
            redirect_to @job
        else
            render "New"
        end
    end

    def edit
        
    end

    def update
        if @job.update(jobs_params)
            redirect_to @job
        else
            render "edit"
        end
    end

    def destroy
        @job.destroy
        redirect_to root_path
    end


    private
    def jobs_params
        params.require(:job).permit(:title, :description, :company, :url, :category_id)
    end

    def find_job
        @job = Job.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<h1>New job </h1>

<%= simple_form_for @job  do |f| %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {promt: "Choose a category"}, input_html: { class: "dropdown-toggler"} %>
    <%= f.input :title, label: "Job Title" , input_html: { class: "form-control"}%>
    <%= f.input :description, label: "Job description", input_html: { class: "form-control"} %>
    <%= f.input :company, label: "Your company", input_html: { class: "form-control"} %>
    <%= f.input :url, label: "Link to Job", input_html: { class: "form-control"} %>
    <%= f.button :submit %>
<% end %>

app/views/jobs/edit.html.erb
<%=  "Edit Job" %>

<%=  render 'form' %>

<%= link_to "Back", root_path %>

app/views/jobs/index.html.erb
<div id="jobs">
    <% @jobs.each do |job| %>
        <div class="job">
            <h2><%= link_to job.title, job %></h2>
            <p><%= job.company %></p></div>
    <% end %>
  
</div>

app/views/jobs/new.html.erb
<%=  render 'form' %>

<%= link_to "Back", root_path %>

app/views/jobs/show.html.erb
<div id="jobs">
    <div class="job">
        <h2><%= @job.title %></h2>
        <h4><%= @job.description %></h4>
        <h4><%= @job.company %></h4>
        <button class="btn btn-default">
            <%= link_to "Apply for Job", @job.url %>
        </button>
    </div>
</div>
<div id="links">
    <%= link_to "Back", root_path, class: 'btn btn-sm btn-default' %>
    <%= link_to "Edit", edit_job_path(@job), class: 'btn btn-sm btn-default'%>
    <%= link_to "Delete", job_path(@job), method: :delete, data: {confirm: "Are you sure?" }, class: 'btn btn-sm btn-default'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JobBoard</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container">
        <ul class="nav navbar-nav">
          <li class="navbar-brand"> IT Jobs </li>
          <li> <%= link_to "All Jobs", root_path %></li>
          <% Category.all.each do |category| %>
            <li><%= link_to category.name, jobs_path(category: category.name) %></li>
          <% end %>
        </ul>
        <p class="navbar-text float-right">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
          <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
        <% end %>
        </p>
        <%= link_to "if user.admin - link.to New Job", new_job_path, class: "navbar-text navbar-right navbar-link"%>
      </div>
    </nav>
    <div class="container">
      <div class="col-md-6 col-md-offset-3"></div>
      <% if notice %>
       <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
       <p class="alert alert-danger"><%= alert %></p>
      <% end %>
      <%= yield %>
      </div>
  </body>
</html>